[phases.setup]
nixPkgs = ['php84', 'nodejs', 'npm']

[variables]
PHP_VERSION = '8.4'

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci', 'npm run build']

[phases.build]
cmds = ['php artisan config:clear', 'php artisan cache:clear']

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --force && php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT'
