services:
  - type: web
    name: moviehub
    runtime: docker
    plan: free
    branch: main
    envVars:
      - key: APP_NAME
        value: MovieHub
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: OMDB_API_KEY
        value: 72af6cc3
      - key: OMDB_API_URL
        value: http://www.omdbapi.com/
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: moviehub-db
          property: connectionString

databases:
  - name: moviehub-db
    plan: free
    databaseName: moviehub
    user: moviehub
